'''
Erros Personalizados
'''

class FatecError(Exception):
    pass